name: Daily Auto Commit

on:
  schedule:
    # Runs every day at 09:00 UTC (adjust hour/minute if needed)
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update file with email 24f2003594@ds.study.iitm.ac.in
        run: |
          echo "Last update: $(date -u)" > daily_update.log

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "24f2003594@ds.study.iitm.ac.in"
          git add .
          git commit -m "Daily auto-update: $(date -u)" || echo "No changes to commit"
          git push
